/**
 * OCR Prompts — High-accuracy prompts for Gemini vision models
 * Designed for Indian township naksha (site layout plan) extraction.
 * Updated for maximum accuracy — no token budget constraints.
 */

/* ─── Tile Plot Extraction Prompt ──────────────────────────────────────────── */

const PLOT_TILE_PROMPT = [
  'You are a highly specialized real-estate layout plan (naksha) extractor with expert-level proficiency',
  'in reading Indian township site plans. Your task is to extract every individual saleable plot from this zoomed tile image.',
  '',
  '═══════════════════════════════════════════',
  'CONTEXT: WHAT IS A NAKSHA TILE?',
  '═══════════════════════════════════════════',
  'This image is a cropped tile from a larger township layout map. Indian nakshas typically show:',
  '- Rectangular or irregular plot boxes arranged in rows/columns',
  '- Plot size printed inside each box (e.g. "200 Sq.Yd.", "100 SY", "400 sq.yd", "215 Sq.Yd.")',
  '- Block labels (A, B, C, D etc.) — usually printed at section header or inside the plot',
  '- Plot numbers (e.g. 101, 202, A-15) — optional, not always present',
  '- SOLD stamps — red/dark "SOLD" or "SOLD OUT" text overlaid on sold plots',
  '- Roads, paths, parks, green belts — these are NOT plots (ignore them)',
  '- Site Office, Other Site, Club House, amenity areas — NOT saleable plots (ignore)',
  '- Borders, legends, north arrows, logos — NOT plots (ignore)',
  '',
  '═══════════════════════════════════════════',
  'STEP-BY-STEP EXTRACTION PROCESS (follow strictly in order)',
  '═══════════════════════════════════════════',
  'STEP 1 — Scan the entire image systematically. Divide the tile mentally into a 3x3 grid and inspect each cell.',
  'STEP 2 — Identify every pale/light-colored (yellow, cream, white, light-green) rectangular box that represents a saleable land plot.',
  'STEP 3 — For each box, read the text inside and carefully observe its COLOR:',
  '  a) Area/size text → sellableSqYrd (numeric only)',
  '  b) Plot number → plotNo (if printed, e.g. "101", "A-5", "P-23")',
  '  c) Block letter → block (A/B/C/D etc.)',
  '  d) Color/Status → status. STRICT RULE: If the plot color is GREEN, it is "AVAILABLE". If the plot color is RED, it is "SOLD".',
  'STEP 4 — Record the CENTER of each plot box as percent of THIS tile image (0 to 100 for both X and Y axes).',
  'STEP 5 — Double-check: did you miss any small plots near the edges? Check all four corners and all edges.',
  '',
  '═══════════════════════════════════════════',
  'FIELD RULES',
  '═══════════════════════════════════════════',
  '- sellableSqYrd: Extract the NUMBER only.',
  '  Examples: "400 Sq.Yd." -> 400 | "200 SY" -> 200 | "100 sq.yd." -> 100',
  '  If units are sq.ft., convert: divide by 9 (1 sq.yd = 9 sq.ft). "1800 sq.ft" -> 200.',
  '- label: Full area text as printed (e.g. "400 Sq.Yd.", "200 SY", "100 sq.yd.").',
  '- plotNo: The actual plot number/identifier ONLY if printed on the plot.',
  '  DO NOT use the area size as plot number. Leave "" if not visible.',
  '- block: Single letter or block code visible in or near this tile. Leave "" if not visible.',
  '- status: Pay close attention to the COLOR of the plot.',
  '           If the plot area or marker is GREEN, it MUST be "AVAILABLE".',
  '           If the plot area or marker is RED, or if it has a heavy SOLD stamp, it MUST be "SOLD".',
  '           "BOOKED" if BOOKED/HOLD/RESERVED text appears.',
  '           Default to "AVAILABLE" for uncolored/neutral plots without SOLD text.',
  '- markerXPercent: Horizontal center of the plot box as percentage of THIS TILE width (0.0 to 100.0).',
  '- markerYPercent: Vertical center of the plot box as percentage of THIS TILE height (0.0 to 100.0).',
  '',
  '═══════════════════════════════════════════',
  'DISAMBIGUATION RULES',
  '═══════════════════════════════════════════',
  '- Overlapping boxes: If two boxes share a boundary, they are TWO separate plots — extract both.',
  '- Roads between plots: A white/grey strip between plot boxes is a road — do NOT count as a plot.',
  '- Site Office / Other Site: Named office areas — do NOT extract as plot.',
  '- Partial plots at tile edge: If a plot box is cut off at tile boundary, still include it if area is readable.',
  '- Marketing text ("RERA APPROVED", phone numbers, developer name): Ignore completely.',
  '- Amenity boxes (Park, Garden, Club House, Swimming Pool, Temple): Facilities — do NOT extract.',
  '- North arrow, scale bar, legend: Ignore.',
  '- Typical plot count per tile: 6 to 25 plots. If you see fewer than 5, double-check — you may have missed some.',
  '',
  '═══════════════════════════════════════════',
  'COORDINATE CALIBRATION',
  '═══════════════════════════════════════════',
  'markerXPercent = (plotCenterX / tileImageWidth) x 100',
  'markerYPercent = (plotCenterY / tileImageHeight) x 100',
  'Be precise — these coordinates are used to pin markers on the map. Errors > 3% cause wrong marker placement.',
  '',
  '═══════════════════════════════════════════',
  'OUTPUT FORMAT — STRICT JSON ONLY',
  '═══════════════════════════════════════════',
  'Return ONLY valid JSON. No markdown. No prose. No code fences. Start with { and end with }.',
  '',
  '{"plots":[',
  '  {"label":"400 Sq.Yd.","plotNo":"101","block":"A","sellableSqYrd":400,"status":"AVAILABLE","markerXPercent":24.5,"markerYPercent":37.8},',
  '  {"label":"200 Sq.Yd.","plotNo":"","block":"B","sellableSqYrd":200,"status":"SOLD","markerXPercent":68.2,"markerYPercent":51.0}',
  ']}',
  '',
  'CRITICAL FINAL REMINDERS:',
  '1. Extract EVERY plot box — do NOT skip any.',
  '2. Do NOT invent plots. Only extract what is visually present.',
  '3. Do NOT merge adjacent plots into one.',
  '4. Output valid JSON only — no trailing commas, no comments, no extra text.',
  '5. If this tile contains no saleable plots at all, return {"plots":[]}'
].join('\n');

/* ─── Sold-Stamp Pass Prompt ────────────────────────────────────────────────── */

const SOLD_STAMP_PROMPT = [
  'You are reading a FULL township naksha (site layout plan) image to find SOLD plots ONLY.',
  '',
  '═══════════════════════════════════════════',
  'YOUR SINGLE TASK',
  '═══════════════════════════════════════════',
  'Find every saleable plot rectangle/circle that has ANY of these sold indicators:',
  '- The plot area or its marker/circle is colored RED',
  '- Text: "SOLD", "SOLD OUT", "S.O.", "बिक गया", "बिका"',
  '- A clear red, dark, or diagonal stamp overlaid on the plot box',
  '- A heavy cross (X) or hatching pattern indicating sold',
  '',
  'IGNORE:',
  '- Roads, paths, green belts, parks',
  '- Site Office, Other Site, Club House, amenities',
  '- Developer logos, phone numbers, RERA text, marketing text',
  '- Available/unsold plots (i.e. GREEN colored plots or uncolored plots with no SOLD text)',
  '- BOOKED/HOLD plots (report those as SOLD if you cannot distinguish)',
  '',
  '═══════════════════════════════════════════',
  'FOR EACH SOLD PLOT',
  '═══════════════════════════════════════════',
  '- label: Area text printed inside (e.g. "400 Sq.Yd.")',
  '- sellableSqYrd: Area number only (e.g. 400)',
  '- status: Always "SOLD"',
  '- markerXPercent: Center of SOLD plot box as % of FULL IMAGE width (0 to 100)',
  '- markerYPercent: Center of SOLD plot box as % of FULL IMAGE height (0 to 100)',
  '',
  '═══════════════════════════════════════════',
  'COORDINATE PRECISION',
  '═══════════════════════════════════════════',
  'markerXPercent = (plotCenterX / fullImageWidth) x 100',
  'markerYPercent = (plotCenterY / fullImageHeight) x 100',
  'These are used to cross-reference with tile-extracted plots. Accuracy within +/-2% is critical.',
  '',
  '═══════════════════════════════════════════',
  'OUTPUT — STRICT JSON ONLY',
  '═══════════════════════════════════════════',
  'Return ONLY valid JSON. No markdown. No prose. No extra text.',
  '',
  '{"plots":[',
  '  {"label":"400 Sq.Yd.","sellableSqYrd":400,"status":"SOLD","markerXPercent":18.2,"markerYPercent":51.4}',
  ']}',
  '',
  'If ZERO plots are sold: return {"plots":[]}',
  'NEVER fabricate SOLD status. Only mark as SOLD if you can clearly see the sold indicator.'
].join('\n');

/* ─── Project Meta Extraction Prompt ───────────────────────────────────────── */

const META_PROMPT = [
  'You are reading a township naksha (site layout plan) to extract ONLY marketing/project metadata — NOT plot inventory.',
  '',
  'Look for and extract:',
  '1. Location name (city, town, tehsil, district, state) — often printed in large text at top',
  '2. Survey number(s) printed on the map (e.g. "Survey No. 427", "S.No. 12/1")',
  '3. Village name (gram/village the land belongs to)',
  '4. Key highlights (e.g. "RERA Approved", "Highway Frontage", "Gated Township", "NA Land")',
  '5. Location advantages (distances to landmarks: e.g. "5 Km from Airport", "500m from Highway")',
  '6. Amenities listed in legend or on map (e.g. Park, Club House, Temple, Swimming Pool, School)',
  '',
  'DO NOT extract plot data or plot counts.',
  'DO NOT extract developer phone numbers or emails.',
  'DO NOT guess or invent any values — only use text that is visibly printed.',
  '',
  'Return STRICT JSON only. No markdown. No prose:',
  '{"projectMeta":{"location":"","surveyNumber":"","village":"","highlights":[],"locationAdvantages":[{"distance":"","landmark":""}],"amenities":[]}}'
].join('\n');

/* ─── Config ────────────────────────────────────────────────────────────────── */

/** Use maximum available output tokens — naksha images can have 30+ plots per tile */
const MAX_OUTPUT_TOKENS = 65536;

module.exports = { PLOT_TILE_PROMPT, SOLD_STAMP_PROMPT, META_PROMPT, MAX_OUTPUT_TOKENS };
